wireframe/wireframe/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'wireframe.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^', include('wireframe.archiveit.urls', namespace='archiveit')),
    # TODO: add urls for account system.
    #url(r'^account/$', include(wireframe.accounts.urls)),
    url(r'^admin/', include(admin.site.urls)),
)

wireframe/wireframe/accounts/models.py
from django.db import models
from datetime import datetime
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic

CONSTANTS = {
    "StorageUnits":(
        ("MB", "MB"),
        ("GB", "GB"),
        ("TB", "TB"),
        ("PB", "PB"),
        ("EB", "EB"),
    ),
    "StorageUnitsToExponents":{
        "MB": 2,
        "GB": 3,
        "TB": 4,
        "PB": 5,
        "EB": 6,
    }
}

# file size helper for StorageQuota
def format_filesize(number):
    for size in ['bytes', 'KB', 'MB', 'GB', 'TB', 'PB']:
       if number < 1024.0 or size == 'PB':
           return "{:.2f} {}".format(number, size)
       number = number / 1024.0

# AccountMessages 
class UserProfile(models.Model):
    user = models.OneToOneField('auth.User')
    account = models.ForeignKey('Account')
    def __str__(self):
        return "[UserProfile] for {}".format(self.user)

class Account(models.Model):
    name = models.CharField(max_length=200, blank=True, default="")
    up_to_date = models.BooleanField(default=False)
    user_quota = models.IntegerField(default=10)
    storage_quota = models.OneToOneField('StorageQuota')
    created_on = models.DateTimeField(null=True, blank=True)
    def save(self, *args, **kwargs):
        if not self.pk:
            self.created_on = datetime.now()
        super(Account, self).save(*args, **kwargs)
    def __str__(self):
        return "[Account] {}".format(self.name)

class AccountMessage(models.Model):
    message = models.TextField(blank=True, null=True)
    account = models.ForeignKey("accounts.Account")
    viewed = models.BooleanField(default=False)
    viewed_on = models.DateTimeField(blank=True, null=True)
    created_on = models.DateTimeField(blank=True, null=True)
    target_url = models.CharField(max_length=200, blank=True, null=True)
    def __str__(self):
        return "[Message] for {}".format(self.account)
    def save(self, *args, **kwargs):
        if not self.pk:
            self.created_on = datetime.now()
        if self.viewed and not self.viewed_on:
            self.viewed_on = datetime.now()
        super(AccountMessage, self).save(*args, **kwargs)

class StorageQuota(models.Model):
    amount = models.IntegerField(default=500)
    units = models.CharField(max_length=2, choices=CONSTANTS['StorageUnits'])
    def storage_used(self, human_readable=True):
        unit_conversion = (1024 ** CONSTANTS['StorageUnitsToExponents']['GB'])
        # TODO: 523.51 GB is just stubbed in here as a constant. This should lookup the actual storage consumed for the account.
        used = (523.51 * unit_conversion)
        if human_readable:
            return format_filesize(used)
        return used
    def storage_available(self, human_readable=True):
        unit_conversion = (1024 ** CONSTANTS['StorageUnitsToExponents'][self.units])
        available = (self.amount * unit_conversion) - self.storage_used(human_readable=False)
        if human_readable:
            return format_filesize(available)
        return available
    def __str__(self):
        return "StorageQuota"

wireframe/wireframe/archiveit/models.py
from django.db import models
import jsonfield
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic
from datetime import datetime


CONSTANTS = {
    'SeedFrequency': (
       ('0', 'One Time'),
       ('1', 'Daily'),
       ('7', 'Weekly'),
       ('30', 'Monthly'),
       ('365', 'Yearly'),
       ('3650', 'Once per Decade'),
    ),
    'SeedScopeRuleTypes':(
       ('contains', "If the URL contains the following text:"),
       ('startswith', "If the URL starts with the following text:"),
       ('endswith', "If the URL ends with the following text:"),
       ('matches', "If the URL matches the Regular Expression:")
    )
}

# Collections represent 
class Collection(models.Model):
    name = models.CharField(max_length=100)
    owner = models.ForeignKey("accounts.Account", blank=True, null=True)
    public = models.BooleanField(default=False)
    metadata = jsonfield.JSONField()
    active = models.BooleanField(default=True)
    topics = models.ForeignKey('CollectionTopic', blank=True, null=True)
    created_on = models.DateTimeField(blank=True, null=True)
    updated_on = models.DateTimeField(blank=True, null=True)
    last_crawl = models.DateTimeField(blank=True, null=True)
    comments = generic.GenericRelation('Comment')
    def next_crawl_date(self):
        return datetime.now + datetime.timedelta(7)
    def __str__(self):
        return "[Collection]".format()
    def save(self, *args, **kwargs):
        #TODO: set owner here.
        if not self.pk:
            self.created_on = datetime.now()
        self.updated_on = datetime.now()
        super(Collection, self).save(*args, **kwargs)

# CollectionTopics exist to 
# They are shared between all users.
class CollectionTopic(models.Model):
    name = models.CharField(max_length=200)
    def __str__(self):
        return self.name

# this function provides the default folder for Seeds
def get_uncategorized_seed_folder():
    return SeedFolder.objects.get_or_create(name='Uncategorized')[0]

# Seeds represent the URL from which a Crawl should commence, as well as a 
# frequency schedule
class Seed(models.Model):
    url = models.URLField(max_length=200)
    collection = models.ForeignKey('Collection')
    owner = models.ForeignKey("accounts.Account", blank=True, null=True)
    frequency = models.CharField(max_length=3, choices=CONSTANTS['SeedFrequency'])
    capture = models.ForeignKey('SeedCapturePattern', blank=True, null=True)
    public = models.BooleanField(default=False)
    login = models.BooleanField(default=False)
    folder = models.ForeignKey('SeedFolder', blank=True, null=True, default=get_uncategorized_seed_folder)
    metadata = jsonfield.JSONField(blank=True, null=True)
    comments = generic.GenericRelation('Comment')
    #def next_crawl_date():
    #    crawl in self.crawl_set.():
            
    def __unicode(self):
        return "[Seed] {}{}{}".format(self.url, self.public and " (public)", self.frequency and " frequency: " + self.frequency)

# SeedCapturePatterns are a list of filetypes patterns for seeds to capture. They're set up as a class so they can be administered through the admin.
class SeedCapturePattern(models.Model):
    name = models.CharField(max_length=100)
    mimetype = models.CharField(max_length=200, null=True, blank=True)
    def __str__(self):
        return "{} ({})".format(self.name, self.mimetype)

# SeedScopeRules define boundaries for Crawls spawned by a Seed.
class SeedScopeRule(models.Model):
    collection = models.ForeignKey('Collection', blank=True, null=True)
    seeds = models.ManyToManyField('Seed', blank=True, null=True)
    rule_type = models.CharField(max_length=20, choices=CONSTANTS['SeedScopeRuleTypes'], blank=True, null=True)
    rule_match = models.CharField(max_length=200, blank=True, null=True)
    document_limit = models.IntegerField(default=10000, blank=True, null=True)
    use_document_limit = models.BooleanField(default=True)
    comments = generic.GenericRelation('Comment')
    def print_rule(self):
        return "{}".format(self.rule_type and " URL " + self.rule_type + " '" + self.rule_match + "'" or "")
    def __str__(self):
        return "[SeedScopeRule]{}{}".format(
                   self.rule_type and " URL " + self.rule_type + " " + self.rule_match or "",
                   self.use_document_limit and " limit to " + str(self.document_limit) or "",
               )
    def save(self, *args, **kwargs):
        # save initially, to ensure that we have a primary key when working on the below
        super(SeedScopeRule, self).save(*args, **kwargs)
        # add references to my Collection's Seeds if I have a Collection but no Seeds
        if self.collection and not self.seeds.count():
            self.seeds.add(*[seed for seed in self.collection.seed_set.all()])

# Seed folders are not hierarchical.
class SeedFolder(models.Model):
    name = models.CharField(max_length=100)
    owner = models.ForeignKey("accounts.Account", blank=True, null=True)
    def __str__(self):
        return self.name

# Crawls are created from Seeds, presumably by a cron or Celery like process.
class Crawl(models.Model):
    seed = models.ForeignKey('Seed')
    begun_on = models.DateTimeField()
    ended_on = models.DateTimeField()
    completed = models.BooleanField()
    metadata = jsonfield.JSONField(blank=True, null=True)
    comments = generic.GenericRelation('Comment')
    def __unicdoe__(self):
        #TODO: if self.seed is not strictly necessary here, consider removing it. Triggers a query.
        return "[Crawl] From {} begun {:%Y-%m-%d %H:%i:%s}".format(self.seed, self.begun_on)

# Documents are created by Crawls, after fetching a url.
class Document(models.Model):
    crawl = models.ForeignKey('Crawl')
    body = models.TextField(blank=True, null=True)
    url = models.URLField()
    fetch_date = models.DateTimeField(default=datetime.now)
    metadata = jsonfield.JSONField(blank=True, null=True)
    comments = generic.GenericRelation('Comment')

# Comments can apply to any other object via the 'comment_on' GenericForiegnKey.
class Comment(models.Model):
    comment = models.TextField()
    content_type = models.ForeignKey(ContentType)
    object_id = models.IntegerField()
    comment_on = generic.GenericForeignKey()
    def __str__(self):
        return "[Comment] on {} #{}".format(self.content_type, self.object_id)

wireframe/templates/PAGE-base.html
{% load static %}
<!DOCTYPE html>
<html ng-app="ArchiveIt">
<head>
    <meta charset="utf-8">
    {% block title %}<title>{% if title %}{{ title }}{% else %}Archive-it Wireframe{% endif %}</title>{% endblock %}
    <link rel="stylesheet" href="{% static 'foundation/css/app.css' %}">
    <link rel="stylesheet" href="{% static 'css/nv.d3.min.css' %}">
{% block scripts %}
<script src="{% static 'foundation/bower_components/jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'foundation/bower_components/foundation/js/foundation.min.js' %}"></script>
<script src="{% static 'foundation/js/app.js' %}"></script>
<script src="{% static 'js/angular/angular.min.js' %}"></script>
<script src="{% static 'js/d3.min.js' %}"></script>
<script src="{% static 'js/nv.d3.min.js' %}"></script>
{% endblock %}
<script>
{% block reveal_modal_directive %}
var app = angular.module('ArchiveIt', []);
app.directive('revealModal', function (){
   return function(scope, elem, attrs) {
     console.log($(elem).foundation());
     scope.$watch(attrs.revealModal, function(val) {
        if(val) {           
           $(elem).foundation('reveal', 'open');
        } else {
           $(elem).foundation('reveal', 'close');
        }
     });
   }
});
{% endblock %}
{% block angular %}<!-- this block may be used to inject angular.js code -->{% endblock %}
</script>

</head>
<body>
{% block header %}
  <header class='row'>
    <div class='padding-left padding-top one'>
      <div class='small-12 columns'>
      <div class='medium-1 columns logo show-for-medium-up'><h3 class=''>Partner Logo<h3></div>
      <div class='medium-3 columns member-since show-for-large-up'><br><br>Member since {{ request.user.get_profile.account.created_on|date:"F Y" }}</div>
      <div class='right medium-7 small-12 columns'>
          <div class='row'>
             <div class='small-12 columns'>
                 <div class='right padding-right padding-bottom one user-welcome show-for-medium-up'>
                  Welcome, <a href='/account/'>{{ request.user.get_full_name|default:request.user.username }}</a>
                 </div>
             </div>
          </div>
          <dl class='sub-nav right user-nav show-for-medium-up'>
              <dd><a href="#/account/settings">Account Settings</a></dd>
              <dd><a href="">Help</a></dd>
              <dd><a href="#/account/admin">User Admin</a></dd>
              <dd><a href="#/logout">Log Out</a></dd>
          </dl>
      </div>
      </div>
    </div>
  </header>
  <nav class="top-bar row" data-topbar>
  <section class='top-bar-section small-12 columns'>
  <div class='small-12 columns'>
  <ul class='left'>
    <li><a href="/">Collections</a></li>
    <li><a href="#/crawls">Crawls</a></li>
    <li><a href="#/reports">Reports</a></li>
    <li><a href="#/archive">Archive</a></li>
  </ul>
  </div>
  </section>
  </nav>
{% endblock %}


{% block content_row_start %}<div class='row'><div class='small-12 columns'>{% endblock %}

{% block content_header %}<br><article class='medium-9 columns main'>{% endblock %}

{% block content %}
{% endblock %}

{% block content_footer %}</article>{% endblock %}

{% block rightcolumn_header %}<aside class='medium-3 columns show-for-medium-up'>{% endblock %}
{% block rightcolumn %}
{% endblock %}
{% block rightcolumn_footer %}</aside>{% endblock %}

{% block content_row_end %}</div></div>{% endblock %}

{% block footer %}
  <footer class='row'>
    <div class='12-small columns'>
    <br>
    <dl class="sub-nav">
      <dd class="active"><a href="#">Help</a></dd>
      <dd><a href="#">Submit a Question</a></dd>
      <dd><a href="#">Bookmarklet</a></dd>
      <dd><a href="#">Contact Us</a></dd>
      <dd><a href="#">About Archive It</a></dd>
    </dl>
    <br><br><br><br>
    </div>  
  </footer>
{% endblock %}

{% block help %}
{% endblock %}
{% block foundation_start %}
<script>$(document).foundation();</script>
{% endblock %}
</body>
</html>

wireframe/templates/PAGE-collection_add_metadata.html
{% extends "PAGE-base.html" %}

{% block content %}
{% include "PARTIAL-wizard_steps.html" %}

<h5>Add any metadata needed for this collection. You can use any or all of three metadata 
schemas: Dublin Core, MARC, and MODS. We have suggested some metadata that you can 
choose to add.</h5>
<div class='row'>
<div class='medium-8 columns'>
{% with metadata=collection.metadata %}
{% include "PARTIAL-metadata_grid.html" %}
{% endwith %}

<form action='.' method='POST'>
  <div class='hidden' style='display:none;'>
  {% csrf_token %}
  {% if form.non_field_errors %}
  <div class='small-12 columns form-error'>
    <div class='alert-box' data-alert>{{ form.non_field_errors }}</div>
  </div>
  {% endif %} 

  {% for field in form %}
  <div class='formfield row'> 
    {% if field.errors %}
        {% for error in field.errors %}
            <div class='small-12 columns form-error'><div class='alert-box' data-alert>{{ error }}</div></div>
        {% endfor %}
    {% endif %}
    {% if not field.is_hidden %}
		<div class='small-2 columns'>{{ field.label }}</div>
    {% endif %}
    <div class='small-10 columns'>
    {% if field.name == "metadata" %}
		{% verbatim %}
		<textarea name='metadata'>{{ metadata | json }}</textarea>  
		{% endverbatim %}
    {% else %}
		{{ field }}
    {% endif %}
    </div>
  </div>
  {% endfor %}
  </div>
  <a href='/collection/{{ collection.pk }}/add-seeds/' class='button small uppercase bold secondary margin-right three'>&laquo; Previous</a>
  <input type='submit' class='button small uppercase bold' value='Next &raquo;'></input>
</form>
</div>
</div>
<div class='medium-4 columns show-for-medium-up'>
{% include "PARTIAL-popular_metadata.html" %}
</div>
</div>
	
{% endblock %}

{% block rightcolumn %}
<h5>Help</h5>
<div class='panel'></div>
{% endblock %}

wireframe/templates/PAGE-collection_add_seed_scope.html
{% extends "PAGE-base.html" %}
{% load archiveit_extras %}

{% block content %}
{% include "PARTIAL-wizard_steps.html" %}

<form action='.' method='POST'>
<div class='panel blanktable'>
  {% csrf_token %}
  <table><tbody>
  {% if form.non_field_errors %}
  <tr class='form-error'>
    <td><div class='alert-box' data-alert>{{ form.non_field_errors }}</div></td>
  </tr>
  {% endif %} 
  {% if form.rule_type.errors or form.rule_match.errors %}
        {% for error in field.errors %}
            <tr class='form-error'>
            <td class='alert-box' data-alert>{{ error }}</td>
            </tr>
        {% endfor %}
  {% endif %}
  <tr class='formfield'>
     <td>
       <div class='row collapse'>
         <span class='medium-2 width-20-percent columns form-label'>Block URL:</span>
         <span class='medium-5 columns'>{{ form.rule_type }}</span>
         <span class='medium-4 columns left' style='padding-left:1em;'>{{ form.rule_match }}</span>
       </div>
       </div>
     </td>
  </tr>
  {% if form.use_document_limit.errors or form.document_limit.errors %}
        {% for error in field.errors %}
          <tr class='form-error'>
            <td class='alert-box' data-alert>{{ error }}</td>
          </tr>
        {% endfor %}
  {% endif %}
  <tr class='formfield'>
     <td>
       <div class='width-20-percent form-label'>Document Limit:</div>
       <div class='width-80-percent'>
         {{ form.use_document_limit }} 
         limit the number of documents to 
         <span class='width-30-percent'>{{ form.document_limit }}</span>
       </div>
     </td>
  </tr>
 {% for field in form.hidden_fields %}
    {{ field }}
 {% endfor %}
</tbody></table>
  <div class='width-20-percent'></div>
  <div class='width-80-percent padding-left half'>
    <input type='submit' class='button secondary small border padding-top padding-bottom quarter' value='Add Rule'>
  </div>
</div>
</form>
<div class='margin-bottom four'>
  <a href='/collection/{{ collection.id }}/add-metadata/' class='button secondary uppercase bold small margin-right two'>&laquo; Previous</a>
  <a href='/collection/{{ collection.id }}/review/' class='button uppercase bold small'>Next &raquo;</a>
</div>

{% with rules=collection.seedscoperule_set.all %}
  {% if not rules %}
    <h5>Your Scoping Rules</h5>
    <hr>
    <div class='margin-bottom six'>
    You have not added any rules to this collection yet...
    </div>
  {% else %}
    {% include "PARTIAL-seed_scope_grid.html" %}
  {% endif %}
{% endwith %}

{% endblock %}

{% block rightcolumn %}
<h5>Help</h5>
<div class='panel'></div>
{% endblock %}

wireframe/templates/PAGE-collection_add_seeds.html
{% extends "PAGE-base.html" %}

{% block content %}
{% include "PARTIAL-wizard_steps.html" %}
<h5 class='padding-bottom padding-top one'>Add seeds which are the starting point for your collection</h5>
<div class='panel blanktable'>
<a href='#' class='button secondary padding-top padding-bottom quarter small border right'>Add Seeds in Bulk</a>
<form action='.' method='POST'>
  {% csrf_token %}
  {% include "PARTIAL-form_fields.html" %}
  <div class='width-20-percent'></div>
  <div class='width-80-percent padding-left half'>
    <input type='submit' class='button secondary small border padding-top padding-bottom quarter' value='Add Seed'>
  </div>
</form>
</div>
<div class='margin-bottom three'>
  <a href='/collection/{{ collection.id }}/create/' class='button secondary uppercase bold small margin-right two'>&laquo; Previous Step</a>
  <a href='/collection/{{ collection.id }}/add-metadata/' class='button uppercase bold small'>Next Step &raquo;</a>
</div>


{% with seeds=collection.seed_set.all %}
  {% if not seeds %}
    <h5>Your Seeds</h5>
    <hr>
    <div class='margin-bottom six'>
    You don't have any seeds in your collection yet...
    </div>
  {% else %}
    {% include "PARTIAL-seed_grid.html" %}
  {% endif %}
{% endwith %}

{% endblock %}


{% block rightcolumn %}
<h5>Help</h5>
<div class='panel'></div>
{% endblock %}

wireframe/templates/PAGE-collection_review.html
{% extends "PAGE-base.html" %}

{% block content %}
{% include "PARTIAL-wizard_steps.html" %}

<h5 id='top'>
Review the information you entered. You can edit any of the information before running a crawl.
</h5>
<div class='margin-bottom one'>
	<div class='button secondary uppercase small bold margin-right two'>Run Test Crawl</div>
	<div class='button uppercase small bold margin-right two'>Run Regular Crawl</div>
	<a href="/collection/{{ collection.id }}">View Collection &rsaquo;</a>
</div>

<form action='.' method='POST' class='margin-bottom three'>
	<div class='row'>
	<h5 class='small-8 columns' id='collection-info'>Collection Info</h5>
	<div class='small-4 columns right'>
	  <input type='submit' class='button right tiny uppercase bold nomargin' value='Save Edits'>
	</div>
	</div>
  <div class='panel blanktable'>
  {% csrf_token %}
  {% include "PARTIAL-form_fields.html" %}
  </div>
</form>

<div class='margin-bottom three'>
{% with seeds=collection.seed_set.all %}
  {% include "PARTIAL-seed_grid.html" %}
{% endwith %}
</div>

<div class='margin-bottom three'>
<h5 id='metadata-grid'>Collection Metadata</h5>
{% with key_object=collection %}
{% with editing="false" %}
{% with buttons="true" %}
{% with metadata=collection.metadata %}
  {% include "PARTIAL-metadata_grid.html" %}
{% endwith %}
{% endwith %}
{% endwith %}
{% endwith %}
</div>
</div>

<div class='margin-bottom three'>
{% with rules=collection.seedscoperule_set.all %}
  {% include "PARTIAL-seed_scope_grid.html" %}
{% endwith %}
</div>

<div class='margin-bottom one'>
	<div class='button secondary uppercase small bold margin-right two'>Run Test Crawl</div>
	<div class='button uppercase small bold margin-right two'>Run Regular Crawl</div>
</div>

{% endblock %}


{% block rightcolumn %}
<h5>Help</h5>
<div class='panel'>
<div class='button secondary' onclick='$(document).foundation("joyride", "start");'>Guided Tour</div>
</div>
{% endblock %}

{% block help %}
<ol class='joyride-list' data-joyride>
  <li data-id='top' data-text='Next &raquo;'>
  <p>On this page, you can review the information for your collection, and edit the options you entered during the last few steps.</p>
  </li>
  <li data-id='collection-info' data-text='Next &raquo;'>
  <p>Use this area to edit the title of your new collection here, and set its status to public or private with the checkbox.</p>
  </li>
  <li data-id='seed-grid' data-text='Next &raquo;'>
  <p>If you need to edit your seeds, click [Edit], then make your changes and click [Save Changes]</p>
  </li>
  <li data-id='metadata-grid' data-text='Next &raquo;'>
  <p>Metadata for your collection (which propagates to your seeds) can be edited by clicking [Edit] here.</p>
  </li>
  <li data-id='scope-grid' data-text='Finish'>
  <p>Edit your Scoping rules to make sure you don't crawl too many documents. Click [Edit], then enter your changes, and click [Save Changes] to save.</p>
  </li>
</ol>
{% endblock %}

wireframe/templates/PAGE-partner_home.html
{% extends "PAGE-base.html" %}

{% block content %}
    {% with message_set=request.user.get_profile.account.accountmessage_set.all %}
      {% if message_set %}
        <h5>Messages</h5>
        {% for message in message_set %}
          <div class='alert-box info radius' data-alert>{{ message.message }} {% if message.target_url %}<a href='{{ message.target_url }}'>Details &raquo;</a>{% endif %}<a href='#' class='close'>&times;</a></div>
        {% endfor %}
      {% endif %}
    {% endwith %}

    <h5>Active Collections</h5>
    <a href='/collection/add/' class='button small bold uppercase'>+ Create New Collection</a>
    <table class=''>
      <thead>
	<tr>
      <th>Name</th>
	  <th>Most Recent Crawl</th>
	  <th>Next Scheduled Crawl</th>
	</tr>
      </thead>
      <tbody>
        {% if not active_collections %}
        <tr>
          <td colspan='3'>No collections found.</td>
        </tr>
        {% endif %}
	{% for collection in active_collections %}
	<tr>
	  <td><a href='/collection/{{ collection.id }}/'>{{ collection.name }}</a></td>
	  <td>{{ collection.last_crawl|default:"No Crawls Yet" }}</td>
	  <td>{{ collection.get_next_crawl_date|default:"None Scheduled" }}</td>
	</tr>
	{% endfor %}
      </body>
    </table>

    <h5>Inactive Collections</h5>
    <table class=''>
      <thead>
	<tr>
	    <th>Name</th>
	    <th>Last Crawl</th>
	    <th></th>
	</tr>
      </thead>
      <tbody>
        {% if not inactive_collections %}
        <tr>
          <td colspan='3'>No Inactive Collections</td>
        </tr>
        {% endif %}
        {% for collection in inactive_collections %}
	<tr>
	   <td>{{ collection.name }}</td>
	   <td>{{ collection.last_crawl | default:"No Crawls." }}</td>
	   <td><a href='/collections/{{ collection.id }}/activate/'>Activate Collection</a></td>
	</tr>
        {% endfor %}
      </body>

    </table>
{% endblock %}

{% block rightcolumn %}
    <div>
    <h5>Current Subscription</h5>
    <div id='chart' class="panel">
    <h5>DATA</h5>
    <svg style='width:100%; height:200px;'></svg>
    <script>
    nv.addGraph(function() {
        var chart = nv.models.pieChart()
        .x(function(d){ return d.label; })
        .y(function(d){ return d.value; })
        .color(["#666","#BBB"])
        .showLabels(false)
        .showLegend(false)
        .margin({top:-10, left:-10, bottom:-10, right:-10})
        .donut(true)
        
        d3.select("#chart svg")
        .datum([
            { label: "Used Space", value: "3" },
            { label: "Unused Space", value:"6"}
        ])
        .call(chart);
        
        d3.select("#chart svg")
        .append("text")
        .text("33.3%")
        .attr({dy: "50%", dx: "50%"})
        .style({"text-anchor": "middle", "font-weight": "bold", "font-size": "25px"});

        d3.select("#chart svg")
        .append("text")
        .text("used")
        .attr({dy: "57%", dx: "50%"})
        .style({"text-anchor": "middle", "font-size": "14px"});

        nv.utils.windowResize(function() { chart.update() });
    })
    </script>
    </div>
    <div id='chart2' class="panel">
        <h5>DOCUMENTS</h5>
    <svg style='width:100%; height:200px;'></svg>
    <script>
    nv.addGraph(function() {
        var chart = nv.models.pieChart()
        .x(function(d){ return d.label; })
        .y(function(d){ return d.value; })
        .color(["#666", "#BBB"])
        .showLabels(false)
        .showLegend(false)
        .margin({top:-10, left:-10, bottom:-10, right:-10})
        .donut(true)
        
        d3.select("#chart2 svg")
        .datum([
            { label: "Used Space", value: "4" },
            { label: "Unused Space", value:"5" }
        ])
        .call(chart);
        
        d3.select("#chart2 svg")
        .append("text")
        .text("45.7%")
        .attr({dy: "50%", dx: "50%"})
        .style({"text-anchor": "middle", "font-weight": "bold", "font-size": "25px"});

        d3.select("#chart2 svg")
        .append("text")
        .text("used")
        .attr({dy: "57%", dx: "50%"})
        .style({"text-anchor": "middle", "font-size": "14px"});
        
        nv.utils.windowResize(function() { chart.update() });
    })
    </script>

    </div>
    <h5>All Subscriptions</h5>
    <div class="panel"></div>
    <h5>Help</h5>
    <div class="panel">
    </div>
    </div>
{% endblock %}